# This workflow builds the Java Spring Boot backend using Maven
name: Build Java Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/build-backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/build-backend.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          cd backend
          mvn --batch-mode --update-snapshots clean verify
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: backend/target/*.jar
